spring:
  profiles:
    active: dev
    #active: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: update     # 如果没有表创建,已有表则进行更新
#      ddl-auto: create  # 每次重新生成表
    show-sql: true
